### ISSUE TITLE
Yeoman dependency issue

### ISSUE THREAD

**Issue by ajerrison-manchester** [Alfresco/generator-alfresco-adf-app#362] opened 2022-10-20 08:14 UTC
I have a problem with resolving dependencies - yeoman generator cannot resolve dependencies when trying to execute 'yo alfresco-adf-app'. I've been fiddling a lot but still can't seem to fix the dependencies. Looks like auth0 now requires angular > v12, but that's just the start of it... Please can someone fix? I need to start my ADF app soon!

```
npm WARN config cache-min This option has been deprecated in favor of `--prefer-offline`.
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: adf-cli-acs-template@4.11.0
npm ERR! Found: @angular/common@10.2.5
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^10.0.3" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@">=12.0.0" from @auth0/angular-jwt@5.1.0
npm ERR! node_modules/@auth0/angular-jwt
npm ERR!   @auth0/angular-jwt@"^5.0.2" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

Same steps to reproduce.

Environment:
Angular CLI: 14.2.5 (also tried with earlier versions of CLI back to 10.*)
Node: 16.17.1
Package Manager: npm 8.19.2 (also tried with 7.18.1 like the above contributor).
OS: Windows 10

_Originally posted by @ajerrison-manchester in https://github.com/Alfresco/generator-alfresco-adf-app/issues/341#issuecomment-1270173012_

**Comment by mmrotzek** [comment] 2022-10-26 11:44
I had the same problem and fortunately found a solution for it. 

This looks like this.

yo alfresco-adf-app``  terminates with the described error.

Open package.json in the created project folder and change the following dependency 

- from `"@auth0/angular-jwt": "^5.0.2"` 
- to `"@auth0/angular-jwt": "~5.0.2"`

Now run `npm install`. After that the app starts.

The problem is that `angular-jwt@5.1.0` requires angular >= 12 and ADF uses 10.

**Comment by ajerrison-manchester** [comment] 2022-10-31 09:11
Thank you @mmrotzek, making that simple change does now allow me to use 'yo alfresco-adf-app', albeit with a lot of warning about deprecated libraries etc. So I can get working now!

However the generator still doesn't seem to work when I do that, it comes up with another dependency error (on @wry/context this time), so I'll leave this issue open for now even though I'm up and running myself.

**Comment by DenysVuika** [comment] 2023-01-24 20:15
should be fixed by now, please reopen if still an issue

**Closed by DenysVuika** 2023-01-24 20:15 UTC
