### ISSUE TITLE
 Yeoman generator unable to resolve dependencies

### ISSUE THREAD

**Issue by tuchang** [Alfresco/generator-alfresco-adf-app#341] opened 2022-01-29 08:56 UTC
**Description**:
Attempting to follow the installation steps to create an ADF application, found at this page: https://www.alfresco.com/abn/adf/docs/tutorials/creating-your-first-adf-application/

**Observed behavior:**
Running the "yo alfresco-adf-app" command results in the following dependency errors:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: adf-cli-acs-template@4.7.0
npm ERR! Found: karma@undefined
npm ERR! node_modules/karma
npm ERR!   dev karma@"^6.3.6" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer karma@">=0.9" from karma-jasmine-html-reporter@0.2.2
npm ERR! node_modules/karma-jasmine-html-reporter
npm ERR!   dev karma-jasmine-html-reporter@"^0.2.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
```

Tried both the --force and --legacy-peer-deps flags, as suggested, but still saw the same errors after each attempt.

**Expected behavior:**
The app should be generated without errors.

**Steps to reproduce:**
    1 Follow the installation steps outlined at https://www.alfresco.com/abn/adf/docs/tutorials/creating-your-first-adf-application/.
    2 Run the "yo alfresco-adf-app" command.

**Environment:**
Angular CLI: 13.2.0
Node: 16.13.2
Package Manager: npm 8.1.2 (I also tried npm 7.18.1)
OS: linux x64

**Comment by ajerrison-manchester** [comment] 2022-10-06 14:37
I have a similar problem - yeoman generator cannot resolve dependencies when trying to execute 'yo aflresco-adf-app'. I've been fiddling a lot but still can't seem to fix the dependencies. Looks like auth0 now requires angular > v12, but that's just the start of it...

```
npm WARN config cache-min This option has been deprecated in favor of `--prefer-offline`.
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: adf-cli-acs-template@4.11.0
npm ERR! Found: @angular/common@10.2.5
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^10.0.3" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@">=12.0.0" from @auth0/angular-jwt@5.1.0
npm ERR! node_modules/@auth0/angular-jwt
npm ERR!   @auth0/angular-jwt@"^5.0.2" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

Same steps to reproduce.

Environment:
Angular CLI: 14.2.5 (also tried with earlier versions of CLI back to 10.*)
Node: 16.17.1
Package Manager: npm 8.19.2 (also tried with 7.18.1 like the above contributor).
OS: Windows 10

**Comment by DenysVuika** [comment] 2023-01-24 20:15
should be fixed by now, please reopen if still an issue

**Closed by DenysVuika** 2023-01-24 20:15 UTC
